server:
  port: 8102
spring:
  application:
    name: eureka-provider       #服务提供者的名称，消费者使用到此服务时用到的名称，不支持下划线
  zipkin:
    base-url: http://192.168.229.130:9411   #连接zipkin服务的地址
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8100/eureka/    #服务注册中心的地址路径