spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: "jdbc:mysql://localhost:3306/test01?characterEncoding=utf8&serviceTimezone=utc"
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl  #打印sql语句
    map-underscore-to-camel-case: true                     #使用驼峰命名法
  type-aliases-package: "com.example.m_generation.bean"    #别名的包路径
  mapper-locations: classpath:mybatis/mapper/*.xml         #mapper映射的xml目录（写的sql语句的xml文件）
